#!/bin/bash
#SBATCH --job-name=goDISCent-polySimIBD
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=nbrazeau@med.unc.edu
#SBATCH --ntasks=1
#SBATCH --mem=8G
#SBATCH --time=48:00:00
#SBATCH --output=%j.log

Rscript future_polySimIBD.R 2 > polysim.log
